### PR TITLE
Use passwd and group from libc rather than custom definitions

### PR DESCRIPTION
**Pull request by Arcterus**
Also added miscellaneous changes to make Travis work.

### CODE REVIEW

**Comment by Arcterus** [comment]
@mpkh can you merge this?

**Comment by mpkh** [comment]
@Arcterus no, I have no write access to this fork

**Comment by Arcterus** [comment]
Oh?  Interesting.  I guess it didn't get set up correctly.

**Comment by Arcterus** [comment]
@mpkh alright you should have write access now.

**Comment by mpkh** [comment]
@Arcterus should we PR this change to upstream?

**Comment by Arcterus** [comment]
@mpkh it looks like some of the changes have already been made.  We might want to PR the `struct` removals though.

**Pull request merged**
